### ISSUE TITLE
Show sun or moon in the ASCII art

### ISSUE THREAD

**Issue by ericonr** [chubin/wttr.in#258] opened 2019-01-09 22:49 UTC
During either day or night, the ASCII arts for partly cloudy and rain show a sun behind the clouds. It would be nice if, instead, the system were capable of showing a moon behind the cloud (during the night, and for the night section of the 3-day forecast).

The moon art could be just the sun without any rays and white or blue.

**Comment by msikma** [comment] 2019-05-25 21:35
Duplicate of #52.

**Closed** 2019-05-26 16:49 UTC
Labels: duplicate
