### ISSUE TITLE
Units are not displayed when using different country-codes

### ISSUE THREAD

**Issue by the-saddest-clown** [chubin/wttr.in#755] opened 2022-06-18 12:28 UTC
When running `curl fr.wttr.in/Paris` or `curl wttr.in/Paris?lang=fr` the output don't show units (_Km/h, Km, mm_ except temperature _°C_).
![no_units](https://user-images.githubusercontent.com/83234199/174437444-97bc9661-1c70-46ff-a6f0-48029f9ef13d.png)

However running `curl wttr.in/paris` shows all the units
![units](https://user-images.githubusercontent.com/83234199/174437556-ea568ccb-79f6-464f-8eaf-06587b13cf7d.png)

Linux Mint 20.3 "Una" Xfce.

**Comment by bdejean** [comment] 2022-06-18 17:55
Hello, it is not specific to curl, same behaviour using Firefox.

**Comment by the-saddest-clown** [comment] 2022-06-18 21:30
Obviously not a curl problem yeah.
Same when visiting [https://wttr.in/Paris](https://wttr.in/Paris) on ungoogled-chromium with french as default locale.
However forcing english language [https://wttr.in/Paris?lang=en](https://wttr.in/ennezat?lang=en) display the units correctly, still on ugoogled-chromium.
So there is a problem regarding the french translation of wttr.in, at least the way it is supposed to display the units. I looked in the code for something that may be modified but cannot find it otherwise I woul like to help improving it.

**Comment by vegsplore** [comment] 2022-08-04 11:34
Similar observation: I don't get any units for wttr.in/hamburg or wttr.in/hamburg?lang=de . Can only see units if I set ?lang=en.

Not a problem - still love it. Just wanted to notify :)

**Comment by tobi-the-fraggel** [comment] 2022-08-20 09:27
Can confirm the issue. Units also disappear when using other ways of providing localization.
**For Example:**
_bash.function recommendation in Spanish:_
`curl -fGsS -H "Accept-Language: es" --data-urlencode 0m --compressed "wttr.in/Barcelona"`
_using country subdomain in German:_
`curl de.wttr.in/Berlin`
_switching to imperial units doesn't matter:_
`curl de.wttr.in/Berlin?0u`

I've tested all officially supported locale params according to current output of `:help` result. Interestingly some countries seem to get units. The accuracy of this test is not 100%, but close enough for an approximate esteem. Result shows every country code followed by units found, if any:
```bash
#! /usr/bin/env bash
for country in am ar af be bn ca da de el et fr fa hi hu ia id it lt mg nb nl oc pl pt-br ro ru ta tr th uk vi zh-cn zh-tw;
do 
  echo "Result for ${country}:"
  curl -s ${country}.wttr.in/Berlin?T0 | grep -E "[0-9]{1,2} \w{2}"
done
```
Result:
```
Result for am:
Result for ar:
Result for af:
Result for be:
     \_(   ).   ↘ 15 км/г      
     /(___(__)  10 км          
                1.2 мм         
Result for bn:
Result for ca:
Result for da:
Result for de:
Result for el:
Result for et:
Result for fr:
Result for fa:
Result for hi:
Result for hu:
Result for ia:
Result for id:
Result for it:
Result for lt:
Result for mg:
Result for nb:
Result for nl:
Result for oc:
Result for pl:
Result for pt-br:
Result for ro:
Result for ru:
     \_(   ).   ↘ 15 км/ч      
     /(___(__)  10 км          
                1.2 мм         
Result for ta:
Result for tr:
     \_(   ).   ↘ 15 km/sa     
Result for th:
Result for uk:
     \_(   ).   ↘ 15 км/год    
     /(___(__)  10 км          
                1.2 мм         
Result for vi:
Result for zh-cn:
Result for zh-tw:
```
So only country codes be, ru, tr and uk get at least some unit decorations. All other country codes behave as described previous reporters. Therefore considering to remove "french translation" from issue title seems more feasible. 

wttr.in is an awesome application and I'd love to see this bug fixed. Sadly I don't see myself capable of contributing to the code base. That's above my skill level, I am afraid to admit.

**Comment by chubin** [comment] 2022-10-22 17:58
The problem is fixed now. Please test if it works for you

**Comment by tobi-the-fraggel** [comment] 2022-10-24 16:14
@chubin thx mate - that's a lot better. Fixed for all aforementioned country codes.

`git-bash` users still may have some issues with Arabic characters on a standard English windows installation. That's not an issue of your application though. I am just mentioning it for completion.

**Comment by chubin** [comment] 2022-10-24 16:54
I think it depends on the terminal configuration. There are some known problems with RTL scripts indeed.
But that's true, the problem is not related to this issue.

Great that the problem with the units is fixed now.

**Closed by chubin** 2022-10-24 16:54 UTC
Labels: bug
