### ISSUE TITLE
Feature: add information from https://aqicn.org/

### ISSUE THREAD

**Issue by jmcastagnetto** [chubin/wttr.in#378] opened 2019-11-25 19:48 UTC
The documentation for the API is at  https://aqicn.org/json-api/doc/

**Comment by chubin** [comment] 2019-11-28 08:01
Yes, it would be very good feature to have. We could add it at least to the one line format output and maybe to the `v2` view

**Comment by chubin** [comment] 2020-05-24 18:09
I close this issue as a duplicate of #49, and I hope that this feature will be implemented soon

**Closed by chubin** 2020-05-24 18:09 UTC
