### ISSUE TITLE
Weather Data more than little off

### ISSUE THREAD

**Issue by drewauff** [chubin/wttr.in#567] opened 2021-01-16 03:52 UTC
Can you please add http://www.bom.gov.au as a weather data source.

**Comment by serprinss** [comment] 2021-01-27 08:14
i agree, this should use more government weather api's which generally have quite high rate limits and accurate data.
would be happy to pr

**Comment by chubin** [comment] 2021-02-28 16:54
Thank you for the reference; I've added it to the list of potentially interesting and useful data sources.

I close the issue as duplicate of #523 and #526

**Closed** 2021-02-28 16:54 UTC
Labels: data-source, duplicate
