### ISSUE TITLE
Forecast calls for a partially sunny... night time?

### ISSUE THREAD

**Issue by jmccorm** [chubin/wttr.in#282] opened 2019-03-12 06:17 UTC
Perhaps a bright sun peaking out from behind the clouds isn't an ideal way of representing Partly Cloudy for the Night time period?

![image](https://user-images.githubusercontent.com/18018091/54178644-8e84d880-4464-11e9-8a24-10b92ee1aa8a.png)

**Comment by cmdcolin** [comment] 2019-03-24 21:00
Would also be curious if the oneline format at night could be moon icon instead of sun icon :)

**Comment by vophatechnicus** [comment] 2019-05-24 09:44
Duplicate of Issue #258

...

**Comment by msikma** [comment] 2019-05-25 21:35
This and #258 are actually duplicates of an older issue, #52.

**Comment by chubin** [comment] 2019-05-26 16:48
I think we should close both this and #258 in favor of #52.
And the only reason why #52 is still open (besides the implementation itself, of course)
is the "One weather condition - one notation." controversy.
Probably, we should just implement it and add an configuration option for the "sunny night" format

**Closed by chubin** 2019-05-26 16:48 UTC
