### ISSUE TITLE
v2.wttr.in has no fahrenheit option?

### ISSUE THREAD

**Issue by atobi16** [chubin/wttr.in#620] opened 2021-08-31 17:30 UTC
With wttr.in you can specify results in Fahrenheit, but there seems to be no option for this in v2. Why is that?

**Comment by chubin** [comment] 2021-10-31 10:14
Not yet implemented; no bad intentions of course; it will be implemented in future.
I close this as a duplicate of #376

**Closed** 2021-10-31 10:14 UTC
Labels: duplicate, v2

**Comment by chubin** [comment] 2021-11-07 09:35
@atobi16 
I've added UCSC support for v2.wttr.in. Please test if it works for you.
It should switch automatically to USCS if you are in the US,
otherwise the mode should be activated with `?u`, as usually.

```
$ curl v2.wttr.in/?u
```

If the USCS mode is active:

* The temperature is displayed in Fahrenheit
* The wind-speed is displayed in MpH
