### ISSUE TITLE
WTTR_LISTEN_PORT is ignored

### ISSUE THREAD

**Issue by Artanicus** [chubin/wttr.in#240] opened 2018-11-06 19:15 UTC
WTTR_LISTEN_PORT is not used anymore to override the listening port, it always ends up as 8002. The readme still documents this as a viable option.

**Comment by chubin** [comment] 2020-05-24 16:28
The problem is fixed now. Please write if it does not work for you

**Closed by chubin** 2020-05-24 16:28 UTC
