### ISSUE TITLE
wttr.in shows no degrees centigrade in Opera version 36.0 browser.

### ISSUE THREAD

**Issue by rhus** [chubin/wttr.in#47] opened 2016-07-08 18:04 UTC
wttr.in shows no degrees centigrade in Opera version 36.0 browser, it shows only fahrenheit.

**Comment by chubin** [comment] 2017-03-15 10:18
Is this still relevant? I believe, it is already fixed. Could you please recheck it?

**Comment by chubin** [comment] 2020-05-23 20:16
Should be fixed now. Please comment/reopen if the problem is still there.

**Closed by chubin** 2020-05-23 20:16 UTC
