### ISSUE TITLE
Blue shades in V2

### ISSUE THREAD

**Issue by simphide** [chubin/wttr.in#385] opened 2019-12-27 16:08 UTC
Can somebody explain me the blue shades in the rain section? 

What does the height and the color of the bars mean? Thanks in advance!

**Comment by chubin** [comment] 2019-12-27 18:02
Hi Simon!

Height: precipitation level
Color: precipitation probability

+ also, the values are displayed usually at the peak level in digital form, say: `0.41mm|77%`
so you can derive the rest from these values + from the curve form and color

**Comment by chubin** [comment] 2020-05-25 06:44
I close this as a (subset) duplicate of #440

**Closed by chubin** 2020-05-25 06:44 UTC
Labels: v2
