### ISSUE TITLE
Doesn't work in Opera with built-in VPN

### ISSUE THREAD

**Issue by romanesko** [chubin/wttr.in#72] opened 2017-02-17 06:32 UTC
VPN off
![VPN off](https://monosnap.com/file/2eNfJJ1K6oGwZg2sTedQ1W0qW3s1CE.png)
VPN on
![VPN on](https://monosnap.com/file/nLu86AexXmHzDmo0TXcd6mwZE4QqoZ.png)

Never noticed similar behavior for any other website…

**Comment by chubin** [comment] 2017-02-17 08:24
That's because of caching and queries (queries from one IP) limitations.
These restrictions were important for the initial wttr.in version, but they should not be so strict anymore.
I think we can remove them soon and then this anomaly disappears

**Comment by chubin** [comment] 2020-05-24 18:19
The problem is fixed now, so if you are still using wttr.in and Opera with built-in VPN, please test
(if it still does not work, please comment)

**Closed by chubin** 2020-05-24 18:19 UTC
