### ISSUE TITLE
Unknown location/Capacity limit reached — wttr.in will be back online at 0:00 UTC

### ISSUE THREAD

**Issue by vzaliva** [chubin/wttr.in#522] opened 2020-09-02 04:16 UTC
From command lineL

```
$ curl -s 'wttr.in?format=3&m'
Unknown location; please try ~43.0833231,-73.8712155⏎      
```

**Comment by LaurentFough** [comment] 2020-09-02 05:24
Thought I was the only one.
Even supply the Airport code, or latlon coordinates, results in the same error.
It does return my actual latlon for the "`please try ... `" portion of the error msg, though

**Comment by chubin** [comment] 2020-09-02 06:50
Fixed, please try again

**Comment by vzaliva** [comment] 2020-09-02 15:22
seems to working for me now. Thanks

**Comment by LaurentFough** [comment] 2020-09-02 19:08
> Fixed, please try again

Fixed.
Cheers.

**Comment by e-alfred** [comment] 2020-09-05 12:29
I am still getting this message:

```
curl -s 'wttr.in?format=3&m'
Unknown location; please try ~42.6545,15.64523
```

**Comment by vzaliva** [comment] 2020-09-05 15:17
yes, it re-appeared

**Comment by t89** [comment] 2020-09-05 15:58
Having the same issue. Querying the coordinates doesn't work, also.

**Comment by ilbuonmarcio** [comment] 2020-09-05 23:27
Same here unfortunately

**Comment by chubin** [comment] 2020-09-07 17:17
Sorry guys it was down for a couple of hours two days ago again, but it should be working since that

**Comment by vzaliva** [comment] 2020-09-07 23:33
working again

**Comment by t89** [comment] 2020-09-13 19:57
Same error appearing again.

**Comment by chubin** [comment] 2020-09-16 08:11
@t89 Thomas, thank you for the reporting.
It happens from time to time, but not too often (once a week, or a month, when the load is peaking). I work on stabilization of this part, and at some point the error should disappear completely

**Comment by jorge-barreto** [comment] 2020-10-01 12:27
Hey @chubin 

Sorry to comment on a closed issue, but I thought I should mention that the problem is happening again

Hope you are well!

**Comment by chubin** [comment] 2020-10-01 12:39
@jorge-barreto Yes, we are experiencing an outage at the moment, many apologies. the service will be back online
in 10 hours.

**Comment by chubin** [comment] 2020-10-02 08:17
It is fixed now

**Closed by chubin** 2020-10-02 08:17 UTC

**Comment by t89** [comment] 2020-10-02 23:43
> It is fixed now

It's broken again. 😆

**Comment by chubin** [comment] 2020-10-07 20:22
Yes, it happens from time to time, but I am working on this

**Comment by Gravifer** [comment] 2021-06-17 16:34
Seems another outage?

**Comment by chubin** [comment] 2021-06-17 16:39
Please try now

**Comment by Gravifer** [comment] 2021-06-17 16:57
Working~ thx ;)

**Comment by abouteiller** [comment] 2021-07-22 16:52
Again today

**Comment by byteshiva** [comment] 2021-08-19 06:32
failing out... 
![image](https://user-images.githubusercontent.com/10637299/130019378-34ae457f-36e9-43ab-9b2d-44de19d4d230.png)

**Comment by chubin** [comment] 2021-10-06 11:05
Fixed; please test

**Comment by WuerfelDev** [comment] 2021-10-06 11:08
working, thanks :+1:

**Comment by Rergis** [comment] 2021-10-15 18:37
![Uploading Screenshot_2021-10-15-15-31-43.png…]()
...and again.

**Comment by chubin** [comment] 2021-10-16 11:03
@Rergis It was a different problem, but it is fixed now. Please test it, and please execuse me for the inconvenience

**Comment by timothevs** [comment] 2021-11-03 14:24
Hi, I set up fresh Monterey (macOS 12.0.1) on my new iMac. 

```bash
curl https://wttr.in\?format\="%l:+%C+%t+(%f)+at+%T+%m\n"
```
leads to this error:-
```bash
Unknown location; please try ~<coordinates of my city>%
```

**Comment by chubin** [comment] 2021-11-03 14:41
@timothevs I've just checked your command, and it works fine for me.

Let's try to debug it: what commands from the following list do work:

1. `curl wttr.in`
2. `curl wttr.in/<Your-Location>`
3. `curl wttr.in/<Your-Location>?format=...`

?

**Comment by timothevs** [comment] 2021-11-03 14:51
@chubin , thanks for the quick follow up. VERY strange. Now the command `curl https://wttr.in\?format\="%l:+%C+%t+(%f)+at+%T+%m\n"` works as well, in addition to the three you mentioned.

**Comment by chubin** [comment] 2021-11-03 15:07
Maybe it was a short outage of the data source; it happens from time to time, but not so often

**Comment by I-Pch** [comment] 2022-01-28 12:10
I'm a bit sad this morning 😔 ...

<img width="727" alt="wttr in outage" src="https://user-images.githubusercontent.com/77828085/151544265-0973ca28-87a6-417e-be5d-049659bee678.png">

I can only hope it will get better soon 😊 ...

**Comment by Gskartwii** [comment] 2022-01-28 17:30
Oh, I wasn't aware 1M was the limit, I've been doing a request every minute for `waybar`, so 1.5K requests per day. Sorry about that, maybe I'm partially responsible! What would be a reasonable rate? And could this be helped with some caching?

**Comment by d4n13ls1104** [comment] 2022-01-28 17:52
Having this issue this morning.

**Comment by br0ziliy** [comment] 2022-04-24 19:35
doesn't work again...

**Comment by sssemil** [comment] 2022-04-24 21:56
This issue is back.

**Comment by LemmonPa** [comment] 2022-05-06 22:32
> Oh, I wasn't aware 1M was the limit, I've been doing a request every minute for `waybar`, so 1.5K requests per day. Sorry about that, maybe I'm partially responsible! What would be a reasonable rate? And could this be helped with some caching?

I personally get weather information once every boot, store it in a txt file and use it in bar(get raw default data and get my needed data with tools like grep, sed, sort).if you want more accurate weather information, 3 times a day would be enough. believe me we can predict far more than 1 minute :p

**Comment by chubin** [comment] 2022-06-04 12:34
@CheesyChocolate No, it is fine; we have some caching layers, so feel free to make more queries (as long as it is not 10 queries per second :)

**Comment by compuguy** [comment] 2023-02-20 20:54
Looks like the service has hit the 1M requests limit again:

> Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
> We hope to solve the problem as soon as possible, so you can enjoy
> your favourite weather service 24x365 even if it rains or snows.

**Comment by AkechiShiro** [comment] 2023-08-09 21:47
Has the service hit again the 1M requests limit again ?

**Comment by abstrnoah** [comment] 2024-05-28 19:02
Limit has been hit several days in a row. Should we reopen this issue / is this being handled by another issue of which I'm unaware? Can anything be done about this? I don't know exactly how wttr.in gets its data but is there anything that the community can do to increase the limit?
