### ISSUE TITLE
Sevastopol, Russia should be Sevastopol, Ukraine

### ISSUE THREAD

**Issue by stobenski** [chubin/wttr.in#51] opened 2016-09-22 15:10 UTC
Hi, my location is identified as "Sevastopol, Russia" instead of Sevastopol, Ukraine.

Like a nearby town Simferopol, that identified correctly (Simferopol, Ukraine).

Thanks.

**Comment by fedya** [comment] 2016-09-22 15:44
Sevastopol is Russia, since 2014.

**Comment by stobenski** [comment] 2016-09-22 16:49
@fedya my hometown Sevastopol is military occupied by Russia since 2014, but not is Russia.

http://data.un.org/CountryProfile.aspx?crName=Ukraine

https://en.wikipedia.org/wiki/List_of_military_occupations#Current_military_occupations

**Comment by ivanovyordan** [comment] 2016-10-02 13:05
Sorry guys but your location is fetched from [ip2location](http://www.ip2location.com/).

**Comment by chubin** [comment] 2016-10-02 13:38
That's right. Wttr.in just uses the data that is provided by various geolocation services (not only ip2location by the way). It has no embedded geolocation information. I agree, that there is some inconsistency: why Simferopol should be identified as Ukraine, and Sevastopol as Russia? It should be either both in Russia, or both in Ukraine.

Theoretically, we can rewrite the answer and specify location of Sevastopol/Crimea more precisely.
I see here three options:

1. Don't change anything
2. Until new status of Sevastopol/Crimea is not internationally recognised, show Ukraine/Russia (as it's done on Wikipedia for example) or Crimea (as it's done on SkyScanner for example).
3. Choose country basing on the query origin (for the countries that recognised Crimea/Sevastopol as a part of Russia use Russia and Ukraine otherwise).

What I find by far more strange is that the weather forecast for Sevastopol,+Ukraine and Sevastopol,+Russia is not equal. For example, as I write this, it is 23 – 25 °C in Sevastopol,+Russia and 22 °C in Sevastopol,+Ukraine. That is because of the caching issues on the data provider side, but I think we should correct this issue on our side, and rewrite the Crimea related queries to make the consistent.

**Comment by vburenin** [comment] 2017-02-08 23:08
![image](https://cloud.githubusercontent.com/assets/4350891/22761618/6b92ac96-ee10-11e6-9dec-94c9f3d6633e.png)

**Comment by chubin** [comment] 2017-02-12 12:02
What did you want to say with this screenshot?
The problem is related to geolocation, no to the weather data per se.
Or did I miss your point?

**Comment by fedya** [comment] 2017-02-12 13:22
Swidomite still supporting communist borders, lol.

**Comment by vburenin** [comment] 2017-02-12 15:11
@chubin I suspect I didn't get the point where the problem is. At least one place detects country name correctly.

**Comment by chubin** [comment] 2017-02-12 16:19
@vburenin As far as I understand, the original issue was related to the IP based geolocation. If you are querying  the service from Sevastopol (in the Crimea), it is geolocated as "Sevastopol, Russia", and @stobenski said that it would be better (preciser, correcter etc.) if it was geolocated as "Sevastopol, Ukraine". The problem (all political questions aside) is that we don't control IP location data, we query an external service for it, and if the service says "Sevastopol, Russia" then it is so. Of course we could patch the data, but in this case we should patch all queries related to the Crimean cities (Simferopol, Yalte, Kerch, etc.). On the other hand, if we only begin with such patching activities, should we also patch Donetsk, Tiraspol, Sukhumi, Pristina, etc. It would be probably not bad, but it is rather complicated.

**Comment by fedya** [comment] 2017-02-12 21:44
![spectacle tj7393](https://cloud.githubusercontent.com/assets/598477/22866292/e1fecc08-f184-11e6-8829-e6aec71770f4.png)
Looks not.
At this moment i see Sevastopol/Ukraine instead of Russia, definetly it's a wrong a location due to 2014.

**Comment by vburenin** [comment] 2017-02-12 23:18
@fedya Ukraine is correct location, it is just temporary occupied by russia.

**Comment by fedya** [comment] 2017-02-13 08:55
@vburenin Ukraine is a monster made by communist dictators and of course you MUST respect democratic vote in Crimea.
It's Russia now and you have to go into the acceptance stage.

**Comment by stobenski** [comment] 2017-02-14 22:27
"democratic vote"

![](http://www.smh.com.au/content/dam/images/3/3/w/q/y/image.related.articleLeadwide.620x349.hvful.png/1393910067793.jpg)

**Comment by fedya** [comment] 2017-02-14 23:14
I was in Crimea in 2014 and saw what's happened there.
Like people people stood up the night to vote to go away from Ukraine, of course without Special Forces it would be impossible. But if run second vote there, you KNOW the results, lol, no fools.
And as i said you need to go into the acceptance stage. Plebiscite is a good tool to stay away from failed states made by commie dictators an murderers.

**Comment by stobenski** [comment] 2017-02-15 06:13
I was in 2014, like 2004, like 1994, like 1984 in Crimea and still here, so you fool no one. 

```
without Special Forces it would be impossible
```
This is military occupation.
```
you KNOW the results
```
Results of illegal "referendum" under military occupation? Are you kidding me?
```
you need to go into the acceptance stage
```
If you want to live in alternative reality - okay.

Countries, UN members, that recognized Russian status of Crimea after military occupation and annexation: (**8**)  _Bolivia, Cuba, Nicaragua, North Korea, Sudan, Syria, Venezuela, Zimbabwe_.

Countries, UN members, that **not** recognized Russian status of Crimea after military occupation and annexation: (**184**) _Afghanistan, Albania, Algeria, Andorra, Angola, Antigua and Barbuda, Argentina, Armenia, Australia, Austria, Azerbaijan, Bahamas, Bahrain, Bangladesh, Barbados, Belarus, Belgium, Belize, Benin, Bhutan, Bosnia and Herzegovina, Botswana, Brazil, Brunei Darussalam, Bulgaria, Burkina Faso, Burundi, Cabo Verde, Cambodia, Cameroon, Canada, Central African Republic, Chad, Chile, China, Colombia, Comoros, Congo, Costa Rica, Côte d'Ivoire, Croatia, Cyprus, Czech Republic, Democratic Republic of the Congo, Denmark, Djibouti, Dominica, Dominican Republic, Ecuador, Egypt, El Salvador, Equatorial Guinea, Eritrea, Estonia, Ethiopia, Fiji, Finland, France, Gabon, Gambia, Georgia, Germany, Ghana, Greece, Grenada, Guatemala, Guinea, Guinea-Bissau, Guyana, Haiti, Honduras, Hungary, Iceland, India, Indonesia, Iran, Iraq, Ireland, Israel, Italy, Jamaica, Japan, Jordan, Kazakhstan, Kenya, Kiribati, Kuwait, Kyrgyzstan, Laos, Latvia, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Lithuania, Luxembourg, Madagascar, Malawi, Malaysia, Maldives, Mali, Malta, Marshall Islands, Mauritania, Mauritius, Mexico, Federated States of Micronesia, Monaco, Mongolia, Montenegro, Morocco, Mozambique, Myanmar, Namibia, Nauru, Nepal, Netherlands, New Zealand, Niger, Nigeria, Norway, Oman, Pakistan, Palau, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Poland, Portugal, Qatar, Korea, Moldova, Romania, Rwanda, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines, Samoa, San Marino, Sao Tome and Principe, Saudi Arabia, Senegal, Serbia, Seychelles, Sierra Leone, Singapore, Slovakia, Slovenia, Solomon Islands, Somalia, South Africa, South Sudan, Spain, Sri Lanka, Suriname, Swaziland, Sweden, Switzerland, Tajikistan, Thailand, Macedonia, Timor-Leste, Togo, Tonga, Trinidad and Tobago, Tunisia, Turkey, Turkmenistan, Tuvalu, Uganda, United Arab Emirates, United Kingdom, Tanzania, United States of America, Uruguay, Uzbekistan, Vanuatu, Viet Nam, Yemen, Zambia_

**Comment by vburenin** [comment] 2017-02-15 06:18
This conversation went to a political direction. @fedya is a troll or vatnik or both, no need to waste your time. fight your enemy within, not on github ;)

**Comment by fedya** [comment] 2017-02-15 09:57
@stobenski 

> If you want to live in alternate reality - okay, I don't care.

I'm live in the Real World, "alternate reality" is where Crimea still Ukrostate.

`Crimea and still here, so you fool no one.
`
Yeah, i see another one officer daughter. Perhaps that's okay with other swidomites like @vburenin 
but for people with good mental health  - not.

![spectacle j18382](https://cloud.githubusercontent.com/assets/598477/22968838/1787e9e6-f37d-11e6-8e80-c9714272aca4.png)
![spectacle j18586](https://cloud.githubusercontent.com/assets/598477/22968879/50340a72-f37d-11e6-9def-17a9c9289984.png)


> Results of illegal "referendum" under military occupation? Are you kidding me?

As i said there is possible to rerun Referendum, and you know how people will vote, no fools to live together with african live level commie failed state.

Look at @vburenin great Ukropatriot already personally eurointegrated. Is most amazing things ever, greatest ukrainian patrions prefer to live as far as possible from Ridna Nenka.

@vburenin 

> @fedya is a troll or vatnik or both

Swine-o-mite, plz.

**Comment by vburenin** [comment] 2017-02-15 15:30
@fedya Сколько желчи, ай-ай-яй.
@chubin Почисти плиз этот нерелевантный бред.

**Comment by fedya** [comment] 2017-02-15 15:39
@vburenin
расисткие выходки типа "ватник" оставь для своих темнокожих коллег в Калифорнии, они оценят.

**Comment by chubin** [comment] 2017-02-15 20:46
Ребята, пожалуйста, давайте не будем опускаться до взаимных оскорблений. Это здесь совершенно ни к чему. Понятно, что проблема принадлежности Крыма и Севастополя острая, и у каждого есть своё собственное мнение об этом. Которое, я вас уверяю, не изменится от того, что бы вы здесь ни прочитали и не написали. Существующие точки зрения известны. Обсуждать их здесь нет никакого смысла. 

Я предлагаю, если вас это действительно волнует (не принадлежность Крыма и Севастополя, а наименование соответствующего населённого пункта в wttr.in) сконцентрироваться на технических аспектах проблемы: как сделать так, чтобы предоставляемая пользователю информация была наиболее корректной, непротиворечивой, и при этом не вызывала у него отторжения или внутреннего протеста. 

Какие возможны варианты? Стоит ли делать локализацию информации в зависимости от источника запроса (в качестве отправной точки можно взять список, который приводит @stobenski )? (как это делает Яндекс, например). Или стоит не указывать название страны, а указать вместо этого просто Крым? (как это делает skyscanner). Или лучше указывать название двух стран претендующих на соответствующий город и делать сноску внизу с кратким описанием проблемы (как это делает Википедия)? Или сделать это конфигурируемым/настраевым, чтобы каждый сам мог исправить досадное недоразумение?

Давайте попытаемся перевести обсуждение в эту плоскость

**Comment by fedya** [comment] 2017-02-15 21:57
>делать сноску внизу с кратким описанием проблемы
This

**Comment by romanesko** [comment] 2017-03-02 10:55
Ещё как вариант — просто убрать страну. В мире вроде нет больше крупных Севастополей, чтобы вводить уточнение для избежания неоднозначности.

**Comment by chubin** [comment] 2017-03-02 11:22
В принципе, Севастополи ещё есть https://en.wikipedia.org/wiki/Sebastopol_(disambiguation) и за счёт абберации близости они могут перекрывать пользователям живущим неподалёку далёкий Севастополь в непонятной стране. Плюс проблема же более общая, например, что делать с Донецком, Приштиной, Тайпеем и ещё множеством городов с неопределённым статусом, которые наверняка появятся в ближайшем будущем

**Comment by YogurtTheHorse** [comment] 2021-01-07 18:02
Это не Севастополи, а Себастополи. Оригинал названия, конечно один, но обычно подобные сервисы как раз именно так и делают. Список городов можно регулировать по индексам, например.

Именно так поступает например гугл
![image](https://user-images.githubusercontent.com/4124939/103927581-a1819600-512b-11eb-9502-9b933fb5e573.png)

**Comment by chubin** [comment] 2021-01-07 18:36
Прямой резолвинг имени работает нормально; там речь шла о государственной принадлежности, указываемой при выводе данных

**Comment by chubin** [comment] 2021-01-07 18:38
Кстати, буква в/б тут роли вообще никакой не играет, потому что это зависит от языка + есть города, в которых буква не меняется ни в одном языке (Кембридж и так далее)

**Comment by iago-lito** [comment] 2021-01-08 09:37
> Или стоит не указывать название страны, а указать вместо этого просто Крым?

From a foreign viewpoint, I like this option because it sounds both legitimate and easier to patch. Locations in `wttr.in` are about geography, and not geopolitics. If it is true that "Crimea" refers to the peninsula and not to a particular nation, then I think that `Sevastopol, Crimea` is a correct way to refer to a location with an ambiguous international status.

Of course, it is an exception to display `City, Region` instead of `City, Country`. Therefore, I like the idea that a note be added in these cases to explain objectively why the geopolitical situation in Crimea makes it impossible for `wttr.in` to both remain neutral and yet still refer to Sevastopol in the usual `City, Country` format.

**Comment by chubin** [comment] 2021-01-08 12:56
@iago-lito Fully agree with you, and even more, if we are talking about names resolution, all of them work:

* Sevastopol
* Sevastopol,Russia
* Sevastopol,Ukraine

and they resolve to the same or almost the same point:

```
$ for i in Sevastopol Sevastopol,Ukraine Sevastopol,Russia Sevastopol,Crimea; do curl -ks wttr.in/$i | grep Location: | sed 's/.*\[/[/' ; done
[44.6054434,33.5220842]
[44.5547288,33.4720239]
[44.6866456,33.56698542685506]
[44.5789147,33.5187253]
```
And in the result, you see the location in that form how you specified it in the query.
If for you Sevastopol is in Russia, then for wttr.in it is in Russia; if it is in Ukraine, then it is Ukraine. wttr.in knows that you know it better:

```
$ curl wttr.in/Sevastopol,Ukraine?0
Weather report: Sevastopol,Ukraine

   _`/"".-.     Patchy rain possible
    ,\_(   ).   8..9 °C
     /(___(__)  ↖ 10 km/h
       ‘ ‘ ‘ ‘  10 km
      ‘ ‘ ‘ ‘   0.1 mm

$ curl wttr.in/Sevastopol,Russia?0
Weather report: Sevastopol,Russia

   _`/"".-.     Patchy rain possible
    ,\_(   ).   8..9 °C
     /(___(__)  ↖ 9 km/h
       ‘ ‘ ‘ ‘  10 km
      ‘ ‘ ‘ ‘   0.1 mm
```

Weather (or weather representation) does not change based on the fact what state this particular location currently belongs to. 
So in my opinion, there is not much to discuss, and we should close this issue and concentrate our efforts on issues of higher relevance

**Comment by chubin** [comment] 2021-01-08 12:59
I mark this as `fixed+wating-for-feeback`; if you find that there are things to be fixed here, please comment; by default the issue will be closed after some time

**Comment by YogurtTheHorse** [comment] 2021-01-09 14:27
Just wanted to mention that Sevastopol is not a part of Crimea like Moscow isn't a part of Moscow Oblast', so Sevastopol, Crimea is not fully correct

**Comment by YogurtTheHorse** [comment] 2021-01-09 14:31
A great solution, btw

**Comment by chubin** [comment] 2021-01-09 15:26
Yes, I know that; from administrative perspective it is not part of Crimea neither in Russia, nor in Ukraine (I lived in Sevastopol for many years, back in times when there was even a controlled administrative border between Sevastopol, and the rest of the Crimea, so yes I know; but at the same time, geographically speaking, which is more important for weather, Sevastopol is a part of the Crimea; in any case, the full location line under the forecast specifies it precisely) (@YogurtTheHorse  btw, not directly related to Sevastopol, but I was happy to see it in your profile: both of my parents graduated from ITMO, it was LITMO in that days :) Great choice!)

**Closed** 2021-02-27 16:05 UTC
Labels: fixed
