### ISSUE TITLE
Oakville, USA should be Oakville, Canada

### ISSUE THREAD

**Issue by 9000-volts** [chubin/wttr.in#32] opened 2016-04-05 23:38 UTC
My location is identified as Oakville, United States of America instead of Oakville, Canada.

**Comment by nylen** [comment] 2016-04-18 00:09
I'm experiencing the same issue.  This is because the location code will usually only return the city name:

https://github.com/chubin/wttr.in/blob/5a7f09d8b933fb538a3e1a84cb9f2046e03bd4ef/bin/srv.py#L185-L195

**Comment by vicendominguez** [comment] 2016-05-11 12:27
Same here... with "Valencia".

It's returned Valencia Venezuela  instead of Valencia Spain Europe ($52.7 billion GDP, older than the other one... etc etc....). No sense :disappointed:

**Comment by Tculp-Dev** [comment] 2016-06-03 23:15
I get Melbourne, Australia instead of Melbourne, Florida, USA

**Comment by tculp** [comment] 2016-06-03 23:17
I get Melbourne, Australia instead of Melbourne, USA (Florida)

**Comment by cikasfm** [comment] 2016-06-10 17:58
The same in Novato, California

**Comment by bhearsum** [comment] 2016-07-08 12:09
Same for "Richmond Hill" (I get Richmond Hill, Georgia, USA, should be Richmond Hill, Ontario, Canada).

**Comment by fosskers** [comment] 2016-09-08 18:21
Same thing with Lytton, British Columbia, Canada. The default Lytton that comes up is in Australia. There are also multiple London's throughout the world, and more than one Vancouver.

**Comment by fosskers** [comment] 2016-09-08 18:24
Turns out you just need to add the country name, like this:

```console
> curl "wttr.in/Lytton, Canada"
```

**Comment by sefffal** [comment] 2017-01-16 17:56
I'm submitted a pull request that I think will fix most of these problems: https://github.com/chubin/wttr.in/pull/61

The problem is I don't think @chubin is maintaining this anymore so perhaps he will not merge it.

**Comment by chubin** [comment] 2017-02-22 19:30
@sefffal I maintain it actually, but there is another small problem indeed. The problem is that the code running on the wttr.in server and the code on github diverged and many changes are uncommitted. The problem with the country name is fixed already on the server (but thank you for the fix anyway). It should work now.

The code will be committed to github soon (see #71).

@9000-volts @nylen @vicendominguez @cikasfm @bhearsum @fosskers Please check if geolocation works for you now. It should work (please check wttr.in without any additional locations).

**Comment by chubin** [comment] 2017-02-22 19:39
Similar issues/duplicates: #36 #63

**Comment by chubin** [comment] 2017-03-15 10:11
Fixed

**Closed by chubin** 2017-03-15 10:11 UTC
