### ISSUE TITLE
one-line output mode response omits the negative sign for celcius temperatures below freezing

### ISSUE THREAD

**Issue by gvoysey** [chubin/wttr.in#689] opened 2021-12-20 15:22 UTC
<img width="396" alt="image" src="https://user-images.githubusercontent.com/3641839/146790573-fe2b7126-6c36-4adb-ad23-e41f90610da5.png">

For temperatures below freezing, this should read -5 C. 

The normal display is correct: 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/3641839/146790809-71fe5d39-450d-4c31-94c6-c2032b1042d5.png">

**Comment by misuchiru03** [comment] 2022-01-28 16:33
I see the negative sign for the below-freezing temp in your screenshot. The thermometer character is actually behind the minus, but the minus is sitting right along the curve of the bulb. I add a space after my special characters to account for the font width when using something like FontAwesome. I think adding a space within this format should fix this.
![image](https://user-images.githubusercontent.com/22798851/151584972-47a29f9b-1f34-4b48-a480-0cf0c33861b1.png)

**Comment by chubin** [comment] 2022-03-26 19:20
@misuchiru03 It is a good point, but the problem is that it depends on the terminal. We can't directly affect it. What I can recommend as a workaround: just add spaces between the symbol and temperature:

```
curl wttr.in/?format="%c+++%t"
```

**Comment by chubin** [comment] 2022-03-26 19:21
See also #345

**Comment by chubin** [comment] 2022-06-06 11:57
I close this one; please comment if it should be reopen

**Closed by chubin** 2022-06-06 11:57 UTC
Labels: fixed
