### ISSUE TITLE
curl show weatherin terminal but doesn't show it when I edit .zshrc file for terminal

### ISSUE THREAD

**Issue by bakunjin** [chubin/wttr.in#1041] opened 2024-12-17 14:06 UTC
Hello, 
shortly, I get result in terminal, I get weather when I type in terminal **curl wttr.in/Belgrade?2** but when I add code in .zshrc file I get failure result: it is written  **Weather unavailable now!!!** 

I use Kali linux and I wanted to make my terminal more beautiful, I edited **.zshrc file** and added code for weather:

```
curl wttr.in/Belgrade?2 --silent --max-time 3 > /tmp/now-weather
export readarray aWeather < /tmp/now-weather
rm -f /tmp/now-weather
if [[ "${aWeather[0]}" == "Weather report:"* ]] ; then
    WeatherSuccess=true
    echo "${aWeather[@]}"
else
    WeatherSuccess=false
fi
```

after that I must reload .zshrc file: **source /home/kali/.zshrc** 
then I start my terminal and as I told you, it is written: **Weather unavailable now!!!** 
but **when I try curl command, I get weather result.**
I made screenshot, you can see it, left corner weather report and curl command down.

![curl-problem](https://github.com/user-attachments/assets/74da3669-557a-40f0-82eb-28ef34d025a6)

**Comment by chubin** [comment] 2024-12-17 15:51
Do you know where the message (`Weather unavailable now!!!`) comes from? That's not the service that returns you it. IN your script I don't see this text either. Is it the dashboard software which produces it?

**Comment by bakunjin** [comment] 2024-12-17 18:35
hello, thank you for wish to help, there is message line in the code, just I didn't want to copy paste all lines. because code script is long but here is part of the code about weather in terminal, you can see whole script here: https://askubuntu.com/questions/1020692/terminal-splash-screen-with-weather-calendar-time-sysinfo
```

# Setup for 92 character wide terminal
DateColumn=34 # Default is 27 for 80 character line, 34 for 92 character line
TimeColumn=61 # Default is 49 for   "   "   "   "    61 "   "   "   "

# Replace Edmonton with your city name, GPS, etc. See: curl wttr.in/:help
curl wttr.in/Belgrade?2 --silent --max-time 3 > /tmp/now-weather
# Timeout #. Increase for slow connection---^

export readarray aWeather < /tmp/now-weather
rm -f /tmp/now-weather

# Was valid weather report found or an error message?
if [[ "${aWeather[2]}" == "Weather report:"* ]] ; then
    WeatherSuccess=true
    echo "${aWeather[@]}"
else
    WeatherSuccess=false
    echo "+============================+"
    echo "| Weather unavailable now!!! |"
    echo "| Check reason with command: |"
    echo "|                            |"
    echo "| curl wttr.in/Belgrade?2    |" # Replace Edmonton with your city
    echo "|   --silent --max-time 3    |"
    echo "+============================+"
    echo " "
fi
echo " "                # Pad blank lines for calendar & time to fit

```

**Comment by chubin** [comment] 2024-12-18 06:35
Ok, now it became more clear. Could you please when the error occurs also show the content of `/tmp/now-weather`? (you can remove it afterwards; and by the way, you don't need a file here, you can just save the output into a variable).

**Comment by bakunjin** [comment] 2024-12-18 12:26
Hi, there is RM command in code after array command, it was automatically deleting file in TMP folder, when I disabled this command, file now-weather stayed in TMP folder and when I opened file, inside is written result for weather, so, everything is okay, curl command obviously took the weather information from your server, but when I reloaded **.zshrc** and I started terminal, I got the problem again like before, it is written **Weather unavailable now!!!** it is easier to show you screenshot than to copy 2 days weather output-lines from the file. you can see it in screenshot, there is weather information in temporary file but in terminal there is no weather information. 
I will also upload whole zshrc file so you can see the whole code, (I must add extension txt, github doesnt support upload of zshrc file without extension, the code for weather begins from line 260), but to tell you, **only weather is making problem, I get date and calendar result.** 

![temp](https://github.com/user-attachments/assets/9511e811-5329-4ed8-88cc-4e79835a6fb3)
[zshrc.txt](https://github.com/user-attachments/files/18181083/zshrc.txt)

**Comment by chubin** [comment] 2024-12-18 13:39
It looks like the problem is with the command that should read the command output into the variable.
You can either fix the `readarray` command, or fix the `if` check. For example, you can `grep` for `Weather report` in the file, like this:

```
if grep -q 'Weather report:' /tmp/now-weather
```

(of course the file should be removed after the check and not before it then).

In any case, the service is working properly, and the problem is in your script.
I close the issue, but if you have any questions or need help with the script, feel free to ask them. I will be glad to help.

**Closed by chubin** 2024-12-18 13:39 UTC
