### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by Sergey-Voskresenskiy** [chubin/wttr.in#362] opened 2019-10-12 18:56 UTC
Hi! I love wttr.in! Im use one for my polybar script and dosnt have problems, but now im try use json output in js script (for my home page). Im catch response error in console 

```
Uncaught (in promise) SyntaxError: Unexpected end of input at eval
```
code:
```javascript
const w = fetch("http://wttr.in/?format=j1", { mode: "no-cors" })
      .then(r => r.json())
      .then(data => console.log(data));
```
Im do some wrong?

**Comment by chubin** [comment] 2019-10-12 19:56
I suppose that the problem is not related to wttr.in, at least not directly.

See this for example:

https://stackoverflow.com/questions/43317967/handle-response-syntaxerror-unexpected-end-of-input-when-using-mode-no-cors

**Comment by Sergey-Voskresenskiy** [comment] 2019-10-12 20:45
Thank you for the link, unfortunately its contents only indirectly fit my problem, but having studied the problem in detail, (and tested the same fetch code with other json links, for example the one that gives openweathermap, and with the same code, I received an answer without error ) I found similar problems with other people and the answers were most often, something like this:
```
This may be a problem with the endpoint not passing the appropriate parameters in the response header.
Ask the API developer to include this in the headers:
"Access-Control-Allow-Origin": "*",
"Access-Control-Allow-Credentials": true
```

**Comment by chubin** [comment] 2019-10-15 20:14
Could you please curl the endpoints that work good for you with `curl -vI` and post the output here?
I suppose that some other header is missing

**Comment by thilinaaligent** [comment] 2019-10-16 08:45
from jsonplaceholder

```
curl -vI https://jsonplaceholder.typicode.com/todos/1
* About to connect() to jsonplaceholder.typicode.com port 443 (#0)
*   Trying 172.64.129.28...
* Connected to jsonplaceholder.typicode.com (172.64.129.28) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=sni233425.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
* 	start date: Sep 15 00:00:00 2019 GMT
* 	expire date: Mar 23 23:59:59 2020 GMT
* 	common name: sni233425.cloudflaressl.com
* 	issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> HEAD /todos/1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: jsonplaceholder.typicode.com
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Wed, 16 Oct 2019 08:42:19 GMT
Date: Wed, 16 Oct 2019 08:42:19 GMT
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Content-Length: 83
Content-Length: 83
< Connection: keep-alive
Connection: keep-alive
< Set-Cookie: __cfduid=d8cd196c1bdb311d8f4fd8ffebda4dff41571215339; expires=Thu, 15-Oct-20 08:42:19 GMT; path=/; domain=.typicode.com; HttpOnly
Set-Cookie: __cfduid=d8cd196c1bdb311d8f4fd8ffebda4dff41571215339; expires=Thu, 15-Oct-20 08:42:19 GMT; path=/; domain=.typicode.com; HttpOnly
< X-Powered-By: Express
X-Powered-By: Express
< Vary: Origin, Accept-Encoding
Vary: Origin, Accept-Encoding
< Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true
< Cache-Control: public, max-age=14400
Cache-Control: public, max-age=14400
< Pragma: no-cache
Pragma: no-cache
< Expires: Wed, 16 Oct 2019 12:42:19 GMT
Expires: Wed, 16 Oct 2019 12:42:19 GMT
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< Etag: W/"53-hfEnumeNh6YirfjyjaujcOPPT+s"
Etag: W/"53-hfEnumeNh6YirfjyjaujcOPPT+s"
< Via: 1.1 vegur
Via: 1.1 vegur
< CF-Cache-Status: HIT
CF-Cache-Status: HIT
< Age: 3831
Age: 3831
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
Server: cloudflare
< CF-RAY: 5268bd1f582084b2-HKG
CF-RAY: 5268bd1f582084b2-HKG

< 
* Connection #0 to host jsonplaceholder.typicode.com left intact
```

from wttr.in

```
curl -vI http://wttr.in/Adelaide\&format\=j1         
* About to connect() to wttr.in port 80 (#0)
*   Trying 5.9.243.187...
* Connected to wttr.in (5.9.243.187) port 80 (#0)
> HEAD /Adelaide&format=j1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: wttr.in
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: nginx/1.10.3
Server: nginx/1.10.3
< Date: Wed, 16 Oct 2019 08:44:04 GMT
Date: Wed, 16 Oct 2019 08:44:04 GMT
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
< Content-Length: 8450
Content-Length: 8450
< Connection: keep-alive
Connection: keep-alive

< 
* Connection #0 to host wttr.in left intact
```

**Comment by chubin** [comment] 2020-05-23 19:52
The problem is fixed. Please test

**Comment by chubin** [comment] 2020-06-02 11:28
I close the issue, please comment/open a new one if there are any problems here

**Closed by chubin** 2020-06-02 11:28 UTC
