### ISSUE TITLE
Image depicts sun during nighttime

### ISSUE THREAD

**Issue by silkthyme** [chubin/wttr.in#306] opened 2019-05-30 05:07 UTC
I checked the weather for tonight and the graphic said it would be partly sunny, but the sky is completely black? I don't see the sun anywhere? SO either the sky is wrong, ORRRRR...

**Comment by UnHumbleBen** [comment] 2019-05-30 05:08
I have this issue too

**Comment by chubin** [comment] 2019-05-30 15:24
@silkthyme @UnHumbleBen Actually it should be partially moonny :)

I suppose it is a duplicate of #52. Please check out that issue, and take a look at/comment the beautiful artwork proposed by @msikma

Do you like it?

**Closed by chubin** 2019-05-30 15:24 UTC
