### ISSUE TITLE
GeoIp incorrect for some IPs

### ISSUE THREAD

**Issue by drbayer** [chubin/wttr.in#162] opened 2017-10-26 14:50 UTC
I have noticed that my IP address returns incorrect location. It appears to be pulling data for Antioch, CA but I'm in Nashville, TN (near Antioch, TN).  I checked ip2location, maxminddb and a legacy geoip db, and all return the correct location.  When I check using long/lat, it returns the correct location data.  Perhaps it is finding my IP in a local maxminddb that needs to be updated?

**Comment by merced317** [comment] 2018-02-22 19:42
I too am having an issue with this.  I am in Rochester, NY and am receiving weather for Rochester, UK.

**Comment by chubin** [comment] 2018-10-26 22:21
@drbayer @merced317 
The problem is fixed now (I hope). Please check if it works for you.
And thank you for reporting

**Closed by chubin** 2018-10-26 22:21 UTC

**Comment by chubin** [comment] 2018-10-27 15:28
Yes, this bug was introduced yesterday indeed. It is fixed now, please test. Thank you for reporting!

**Comment by merced317** [comment] 2018-10-27 15:29
Looks great now.  Thanks for the continued awesome work!  Love this project. <3
