### ISSUE TITLE
Unknown location (problem with geolocation)

### ISSUE THREAD

**Issue by 2011** [chubin/wttr.in#576] opened 2021-02-14 08:31 UTC
Just came across wttr.in, and of course, it doesn't work (by default) for me (I did learn about all of the options when coming here).

Anyway:

```
$ curl wttr.in
>>>    _  _    ___  _  _        
>>>   | || |  / _ \| || |         
>>>   | || |_| | | | || |_         
>>>   |__   _| |_| |__   _|         
>>>      |_|  \___/   |_|       
>>>                          
>>>   404 UNKNOWN LOCATION: Seattle47.4902, Washington, United States   
>>>                    
----
Weather report: Oymyakon

[...]

 We were unable to find your location 
 so we have brought you to Oymyakon, 
 one of the coldest permanently inhabited locales on the planet. 
```

It looks like the code sort of discovered (but didn't parse correctly) the location.

**Comment by AlexAegis** [comment] 2021-02-14 11:33
Same thing here!

```
404 UNKNOWN LOCATION: Budapest47.5636, Hungary   
```

**Comment by chubin** [comment] 2021-02-14 22:12
I can acknowledge it. It is a bug

**Comment by lakejason0** [comment] 2021-02-15 11:29
Can acknowledge it. It shows the same pattern of the location.

**Comment by alexeygumirov** [comment] 2021-02-20 22:20
Same for Bonn, Germany:
```
curl -s wttr.in/Бонн\?format=j1
Unknown location; please try ~50.735851,7.10066% 
```

**Comment by rhysday** [comment] 2021-02-20 22:51
Yea it keeps happening. Pretty sure it's the server being overloaded. Annoying but not sure there is much they can do about it?

**Comment by chubin** [comment] 2021-02-27 15:51
In this issue we have three different problems:

1. Real code bug reported by @2011 and confirmed by me.
2. The problem @alexeygumirov reported (`Unknown location; please try`)
3. Geolocation service overload, that happens because of `1` and that causes rejections.

The first bug is now fixed, and the tests are running now. 

The second problem may occur again, when wttr.in goes beyond its daily queries capacity.
We doubled the capacity recently (it will be effectively increased since 1 March 2021),
and so the problem should not occur so often.

The third one will hopefully also disappear, because it was indirectly caused by (1),
that is fixed now

**Comment by alexeygumirov** [comment] 2021-02-28 01:38
Thanks for the fixing. I don't see issue anymore. Everything is fine last days.

**Comment by chubin** [comment] 2021-02-28 08:33
This bug was pretty nasty, it affected almost 100k users in these two weeks:
```
$ ... | wc -l
88573
```
Very good that we fixed it now. Thank you for reporting and thank you for the help

**Closed by chubin** 2021-02-28 08:33 UTC
Labels: bug
