### ISSUE TITLE
500 Internal Server Error with curl (conky)

### ISSUE THREAD

**Issue by vitich** [chubin/wttr.in#278] opened 2019-03-01 06:53 UTC
$ curl  http://wttr.in/Kyiv_0pq_transparency=200_lang=uk.png
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

Tried to add useragent - didn't help

> We are working on that; I hope it will be fixed in two hours

**Comment by chubin** [comment] 2019-03-01 06:55
We are working on that; I hope it will be fixed in two hours

**Comment by vitich** [comment] 2019-03-01 07:11
> We are working on that; I hope it will be fixed in two hours

Sorry! I should have read the message on the main page. :)

**Comment by vovs03** [comment] 2020-03-15 08:06
# 👊 500

![Снимок экрана 2020-03-15 в 11 03 17](https://user-images.githubusercontent.com/21124057/76697821-022b7800-66ad-11ea-9524-328d2ba0735f.jpg)

**Comment by chubin** [comment] 2020-03-15 10:12
@vovs03 Do you still have the problem?

**Comment by chubin** [comment] 2020-05-23 19:54
The problem is fixed. I close the issue. Please comment it, if you will experience the problem again

**Closed by chubin** 2020-05-23 19:54 UTC
