### ISSUE TITLE
Airport code / city name ambiguity

### ISSUE THREAD

**Issue by silentbicycle** [chubin/wttr.in#195] opened 2018-05-10 18:37 UTC
For the airport code GRR (in Grand Rapids, MI) I get a weather report  أبو Grr, مصر (Abu Grr, Egypt). Is there a way to indicate that airport codes should take preference over city names? Case doesn't seem to matter -- "grr" and "GRR" get the same result.

Using a zip code (49506) or the IP-based location seems to work fine, but there may be other ambiguous city/airport code pairs.

**Comment by chubin** [comment] 2018-05-31 14:13
Yes, there was a problem with IATA airport codes indeed. The problem is fixed now, so you can use IATA codes again. They are always preferred to city names by the location resolution algorithm. If you want to use a city name, you should just add + to the end of the location name (grr+ in your example)

**Closed by chubin** 2018-05-31 14:13 UTC

**Comment by AloisMahdal** [comment] 2018-05-31 15:43
As mentioned in #201, airport codes now work properly (testing from Brno IP):

    $ for loc in brq bts rdu grr; do curl -s wttr.in/$loc | grep Location | sed "s/^/$loc|/"; done
    brq|Location: Letiště Brno Tuřany,  904/1,  Jihovýchod,  62700,  Česko [49.1547016,16.691368]
    bts|Location: Letisko (Airport), Ivanská cesta, Bratislava, Bratislavský kraj, 83107, Slovensko [48.1708708,17.2004171]
    rdu|Location: John Brantley Boulevard, Brier Creek, Wake County, North Carolina, 27560, United States of America [35.8768458,-78.7885008]
    grr|Location: Airport Viewing Area, Cascade, Cascade Charter Township, Kent County, Michigan, United States of America [42.87590595,-85.5271788718]
    $

(I'm assuming 'GRR' is correct despite @silentbicycle mentioning "Grand Rapids").

**Comment by chubin** [comment] 2018-05-31 15:56
I think it is the same:
```
curl wttr.in/~GRR | grep ^Location
Location: Grand Rapids, Kent County, Michigan, United States of America [42.9632405,-85.6678638]

curl wttr.in/~Grand+Rapids | grep ^Location
Location: Grand Rapids, Kent County, Michigan, United States of America [42.9632405,-85.6678638]
```

**Comment by silentbicycle** [comment] 2018-05-31 16:16
Correct -- the GRR airport is in Kent County, in the greater Grand Rapids metro area -- it's probably technically more correct to say it's in Cascade.

Thanks!

**Comment by M4444** [comment] 2018-05-31 17:11
Yup, works from my side too ^^

**Comment by AloisMahdal** [comment] 2018-05-31 19:55
@chubin, isn't it strange, though, that I get different description of the location (same coords, though) than you?

    $ curl -s wttr.in/~GRR | grep ^Location
    Location: Airport Viewing Area, Cascade, Cascade Charter Township, Kent County, Michigan, United States of America [42.87590595,-85.5271788718]

(my public IP is 213.175.37.10, Brno, w/o IPv6 connectivity).

**Comment by chubin** [comment] 2018-06-04 07:36
@AloisMahdal I think it is ok; the description is the same, but in my case it was shortened; I was experimenting with the description format (sometimes the description is too long, and I was trying to cut some unneeded things off). But now the description should be consistent everywhere.
