### ISSUE TITLE
mimetype is always html

### ISSUE THREAD

**Issue by rbrich** [chubin/wttr.in#15] opened 2016-02-22 14:44 UTC
The server always sends "Content-Type: text/html; charset=utf-8", even when the content clearly is not HTML. See `curl -I wttr.in`.

It works, but wouldn't it be nicer to send "text/plain" when it's just text, not HTML?

**Comment by chubin** [comment] 2020-05-23 20:10
The problem is fixed now:

```
$ curl -I wttr.in/?Q0
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Sat, 23 May 2020 20:09:50 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 313
Connection: keep-alive
Access-Control-Allow-Origin: *
```

**Closed by chubin** 2020-05-23 20:10 UTC
Labels: bug
