### ISSUE TITLE
PNG rendering in zh-cn and zh-tw

### ISSUE THREAD

**Issue by liyishuai** [chubin/wttr.in#422] opened 2020-03-24 01:36 UTC
Previously mentioned in https://github.com/chubin/wttr.in/issues/119#issuecomment-504399347

http://zh-tw.wttr.in/Taipei.png
![zh-tw](https://user-images.githubusercontent.com/7020805/77379255-a2893880-6d4e-11ea-910d-8349ac09b769.png)

http://zh-cn.wttr.in/Taipei.png
![zh-cn](https://user-images.githubusercontent.com/7020805/77379129-3eff0b00-6d4e-11ea-8500-09e9136d0cbe.png)

**Comment by chubin** [comment] 2020-03-29 18:03
Yes, I know about this problem, but I am not to deep into Chinese, so that I could try to solve it.
Could you please help me, if I write a small python script, which is supposed to generate
the image with this error, and attach it to the issue?

I suppose that there are some Chinese characters missing in the font used at wttr.in

**Comment by liyishuai** [comment] 2020-03-29 20:02
https://github.com/chubin/wttr.in/blob/f3b42a600d29bb680bd52002e02c44f6d0236528/lib/wttrin_png.py#L49-L59
The current Han font only supports common Japanese Kanji, which covers a limited subset of Chinese characters. Consider changing to [Source Han Sans](//blog.typekit.com/2014/07/15/introducing-source-han-sans).
> Source Han Sans, available in seven weights, is a typeface family which provides full support for Japanese, Korean, Traditional Chinese, and Simplified Chinese, all in one font. It also includes Latin, Greek, and Cyrillic glyphs from our popular Source Sans family.

**Comment by chubin** [comment] 2020-03-31 19:27
@liyishuai Than you for the help; the problem is fixed now!

**Closed by chubin** 2020-03-31 19:27 UTC
Labels: bug, help wanted
