### ISSUE TITLE
Changing the source of information (backend)?

### ISSUE THREAD

**Issue by MasterMedo** [chubin/wttr.in#544] opened 2020-11-08 10:40 UTC
I'm trying to get minimal, maximal and current temperature for Zagreb. But no matter which way I try to get it, it simply doesn't make sense. In #491 you say 'Use v2.wttr.in for more accuracy.' Currently it is +3C according to the site, but the minimal and maximal temperatures for today are +5C to +15C. The real low for today was 
+2C. I'm not sure which api you're using but I checked with `wego` and here is what those sources state:

| backend | min | current | max |
| - | - | - | - |
| worldweatheronline.com | 7 | 3 | 15 |
| darksky.net | 2 | 8 | 11 |
| openweathermap.com | 4 | 4 | 10 |

Am I better off just scrapping a local news weather report?
```
curl 'wttr.in/Zagreb?format=v2'
┌┤  Weather report for: Zagreb  ├────────────────────────────────────────┐
│                                                                        │
│                                                                        │
│       Sun 08 Nov              Mon 09 Nov              Tue 10 Nov       │
│                       ╷                       ╷                        │
│                                                                        │
│                                                                        │
│+15         ⢀⠔⠉⠉⠢⡀                                                      │
│           ⢠⠃    ⠑⡄                  ⢀⠤⢄                                │
│          ⢀⠇      ⠈⠢                ⡔⠁  ⠑⢄                    ⣀⢄⣀       │
│          ⡜         ⠑⡄             ⡜      ⠣⡀                ⢀⠎   ⠑⡄     │
│         ⡰⠁          ⠈⢆           ⠜        ⠑⡄              ⢀⠎     ⠈⢣    │
│⡏⠑⠤⡀    ⢠⠃             ⠣⣀  ⡀     ⡜⠁         ⠈⠢⡀           ⢀⠎        ⢇   │
│⡇  ⠈⠢⣀⢀⡠⠃                ⠉⠉⠈⠑⠢⣀⢀⠎             ⠈⠒⢄⡀       ⢀⠎         ⠈⡆  │
│⡇     ⠁                        ⠁                 ⠈⠑⠤⡀   ⡠⠃           ⠸⡀ │
│⡇                                                   ⠈⠉⠉⠉              ⢇ │
│+5                                                                    ⠸⠁│
│                                                                        │
│─────┴─────┼─────┴─────╂─────┴─────┼─────┴─────╂─────┴─────┼─────┴─────╂│
│     6    12    18           6    12    18           6    12    18      │
│                                                                        │
│                                                                        │
│                                                                        │
│                                                                        │
│                                                                        │
│                                                                        │
│                                                                        │
│                                                                        │
│                                                                        │
│ ☀  ☀  ☀  ☀  ☀  ☀  ☀  ☀  ☀  ⛅ ☀  ⛅ ⛅ ⛅ ⛅ ⛅ ⛅ ⛅ ⛅ ⛅ ⛅ ⛅ ⛅ ⛅│
│ ↗  ↗  ↗  ↗  ↑  ↖  ←  ↙  ↓  ↙  ↓  ↓  ↙  ←  ↙  ↓  ↗  ↓  ↖  ↙  ↙  ←  ↙  ↗ │
│ 3  3  3  2  2  2  2  3  3  2  2  2  2  3  3  3  2  1  1  2  3  4  3  3 │
│                                                                        │
│🌗                     🌗                      🌗                     🌘│
│       ─━━━━━━━━━─             ─━━━━━━━━━─             ─━━━━━━━━━─      │
│                                                                        │
│                                                                        │
└────────────────────────────────────────────────────────────────────────┘
Weather: 🌫  Fog, +3°C, 93%, 0km/h, 1028hPa
Timezone: Europe/Zagreb
  Now:    11:09:27+0100 | Dawn:    06:14:27  | Sunrise: 06:46:48
  Zenith: 11:39:47      | Sunset:  16:32:18  | Dusk:    17:04:37
Location: Zagreb, Grad Zagreb, Hrvatska
```

**Comment by rawho** [comment] 2020-11-09 06:58
I would like to work on this issue

**Comment by chubin** [comment] 2020-11-09 08:01
@MasterMedo I agree with you that the backend wttr.in is currently using is pretty inaccurate, and we consider making it configurable (see #523, #526). We already started using OWM in some views (it is used in the v3 view, for example), but the plan is to make the backend configurable. Can you please take a look, does v3.wttr.in seem to be more accurate?

@rawho Rahul, this issue is pretty hard to start from; I suggest you considering one of these ones:

https://github.com/chubin/wttr.in/issues?q=is%3Aissue+is%3Aopen+label%3Aone-line

It is the one-line mode, and it is probably the easiest to start from. Could you please take a look at 
https://github.com/chubin/wttr.in/blob/master/lib/view/line.py and try to understand the code?

**Comment by MasterMedo** [comment] 2020-11-09 08:31
At the moment the temperature is spot on for Zagreb even if the information is very vague, but it doesn't cover Croatia enough to use it (50% of notable places one normally hears in weather reports aren't covered).

![image](https://user-images.githubusercontent.com/16375100/98515634-a03b0680-226b-11eb-97de-3a04c9711061.png)

**Comment by chubin** [comment] 2020-11-09 15:15
@MasterMedo it show the Zagreb region only. Probably, instead of this, the whole Croatia should be displayed? Like we do for Prague, Budapest, or many other capitals. What d you think?

http://v3.wttr.in/Prague
http://v3.wttr.in/Budapest

**Comment by MasterMedo** [comment] 2020-11-18 06:42
I guess that would be nicer for all smaller countries. But still not nice enough. You see, sometimes two relatively close places have completely different forecasts. I'm not big on weather reports, but since I started this issue, I am comparing forecasts from global providers with local ones. I think there is a big enough mismatch to justify using local ones if one finds it crucial when and if a rainfall is expected, or what the \"exact\" temperature is going to be.

On a side note, I think it would make sense to use providers that most phones use (at least that way the information would be consistent across our devices).

**Comment by G2G2G2G** [comment] 2020-12-26 01:09
Seems inaccurate all over. In USA the temp where I am is 20 degrees off (F) and tomorrow it says it's a high of 42 and every other site says high of 61, google, bing, accuweather, wunderground, weather.com, etc. All of them

**Comment by chubin** [comment] 2021-01-02 21:25
@G2G2G2G I think, the problem here could be that it resolved your location wrongly.
There was a bug that was fixed today, that affected many locations in the United States.
Can you please check if you still experience the problem with data accuracy, and if yes, could you give me an example of such a location?

**Comment by G2G2G2G** [comment] 2021-01-03 02:20
@chubin It's still quite a ways off, check out `curl wttr.in/rogers`
The noon on jan 03 says 39..42 in the report, however it says 49-55 everywhere else (currently) 
It says the correct location in the output
```
                                                       ┌─────────────┐                                                       
┌──────────────────────────────┬───────────────────────┤  Sun 03 Jan ├───────────────────────┬──────────────────────────────┐
│            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│               Mist           │    \  /       Partly cloudy  │    \  /       Partly cloudy  │    \  /       Partly cloudy  │
│  _ - _ - _ -  28..+33 °F     │  _ /"".-.     39..42 °F      │  _ /"".-.     44..46 °F      │  _ /"".-.     41 °F          │
│   _ - _ - _   ↑ 4-8 mph      │    \_(   ).   ↑ 5-8 mph      │    \_(   ).   ↗ 3-6 mph      │    \_(   ).   ↑ 1-3 mph      │
│  _ - _ - _ -  4 mi           │    /(___(__)  6 mi           │    /(___(__)  6 mi           │    /(___(__)  6 mi           │
│               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
```

![1](https://user-images.githubusercontent.com/50514477/103470438-e1b1d480-4d37-11eb-9a3c-e21e4d8bd630.jpg)

**Comment by privacy313** [comment] 2021-01-09 12:32
Just adding here that the weather forecasts in Berlin, Germany have also been very inaccurate this week.
It currently reports snow on a totally dry day. It reported snow most of this week when there was none. Daily highs and lows are currently lower by 1 degree (C) compared to accuweather.com
I have tried v2.wttr.in and v3.wttr.in but both seem to be down.

**Comment by chubin** [comment] 2021-02-28 16:57
I close this as a duplicate of #523 and #526

**Closed** 2021-02-28 16:58 UTC
Labels: data-source, duplicate

**Comment by PerfMonk** [comment] 2024-10-23 14:50
Same problem here in Quebec city.  Temperature shown (+8C) are a lot lower than real (+15C).  It makes wttr.in a very unreliable site since it shows random data.
