### ISSUE TITLE
Weather Unit `?u` Isn't Respected For V2

### ISSUE THREAD

**Issue by rjhilgefort** [chubin/wttr.in#604] opened 2021-05-16 19:02 UTC
I'm running the following command and trying to specify USCS/Farenheit, but that option isn't respected.

`curl v2.wttr.in/Evergreen+Colorado\?u`

![image](https://user-images.githubusercontent.com/2034823/118409282-e58b2700-b646-11eb-928d-c41988181931.png)

**Comment by Mist-Hunter** [comment] 2021-06-25 14:14
Same issue for me. I'm sure the environment doesn't matter, but Debian 10.10

**Comment by rifen** [comment] 2021-07-30 16:46
The same for v3 :)

**Comment by chubin** [comment] 2021-10-31 10:51
Yes, this will be implemented. It is a duplicate of #376

**Closed** 2021-10-31 10:55 UTC
Labels: duplicate

**Comment by chubin** [comment] 2021-11-07 09:36
@rjhilgefort @Mist-Hunter @rifen 

I've added UCSC support for v2.wttr.in. Please test if it works for you.
It should switch automatically to USCS if you are in the US,
otherwise the mode should be activated with `?u`, as usually.

```
$ curl v2.wttr.in/?u
```

If the USCS mode is active:

* The temperature is displayed in Fahrenheit
* The wind-speed is displayed in MpH

**Comment by rjhilgefort** [comment] 2021-11-16 00:28
Nice, thanks! It has the correct units now which is fantastic. I don't know if something changed with my font/terminal, but now the icons overflow the box.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/2034823/141873650-37ccbc8a-7537-448e-8abc-809167747b3c.png">

**Comment by chubin** [comment] 2022-03-27 15:30
@rjhilgefort No, Rob, nothing changed except the weather.
That's a know bug (or feature):

* #345

**Comment by rjhilgefort** [comment] 2022-03-27 15:35
@chubin Awesome, good to know. I'll follow that issue, thanks!
